### ISSUE TITLE
How many users can this handle on your laptop ?

### ISSUE THREAD

**Issue by JordanP** [remyleone/chat_demo#4]
Let's say you run this on your laptop (I assume a 2/4 cores, 8/16G of RAM), how many users can send each other messages ? 1000, 10k, 100k ? What's the limiting factor ? 

So more work to do, sorry, but I am intrigued :)

**Comment by sieben** [comment]
I have used this test function as scaling testing: https://github.com/sieben/chat_demo/blob/master/tests/test_scaling.py 

This function starts to get troubles starting at 1000 but I'm not sure why because the RabbitMQ is fine (I can see that using the RabbitMQ monitoring tool). 
I'm probably not using the right methodology for test scaling. I don't know good Python Websocket load testing. Maybe using https://artillery.io or thor would help. 
Maybe it's the tornado event loop that starts to get saturated. If that's would be the case, maybe spawning different tornado process could help reduce the load.

**Comment by JordanP** [comment]
1000 is the max file descriptor limit for a regular (non root) user. Try to relaunch your python processes as root and issue the "ulimit -n 50000" command just before starting your programs.
